### ISSUE TITLE
Typo or error in Installation Instructions

### ISSUE THREAD

**Issue by geraldneale** [geoffwalmsley/CreatorNFT#1]
The part about starting and syncing the DB says this: 
sh

nft init

and looks like this:
![image](https://user-images.githubusercontent.com/53587595/146860155-0fcf969b-642e-4eba-80de-2a5d971aeab1.png)

I don't think that's what you intended and I can't get it to work.

**Comment by geraldneale** [comment]
Upon closer inspection I think this is intended to be "nft init" which still doesn't work, but that is probably because I am on a non-protocol_and_cats_rebased based testnet10.

**Comment by geoffwalmsley** [comment]
hey, thanks. I think it will error out without using protocol and cats because it relies on one of the key derivation functions (master_sk_to_wallet_sk_unhardened) which isn't in main branch yet.
